name: Ask a Question
description: You have questions? Please let us know!
title: "[QUESTION]: <title>"
labels: ["Type: Question"]
body:
  - type: checkboxes
    attributes:
      label: Consent
      options:
        - label: I have searched the existing issues and verified that there is no open issue for the same subject.
          required: true
        - label: I understand that the Loupedeck VoiceMeeter plugin has NO affiliation with VoiceMeeter.com or VB-Audio
          required: true
  - type: textarea
    attributes:
      label: Question
      description: What is your question?
    validations:
      required: true
